# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- script: sudo pip install -U tox
  displayName: 'Install Tox'

- script: tox
  displayName: 'Run tests with tox'

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    testResultsFiles: '**/*.xml' 
    failTaskOnFailedTests: false # Optional
    publishRunAttachments: true # Optional
    
